/**
 * @fileoverview gRPC-Web generated client stub for autodemo
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.12.4
// source: autodemo.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.autodemo = require('./autodemo_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.autodemo.CANSignalServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.autodemo.CANSignalServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.autodemo.Empty,
 *   !proto.autodemo.CANSignal>}
 */
const methodDescriptor_CANSignalService_StreamCANSignals = new grpc.web.MethodDescriptor(
  '/autodemo.CANSignalService/StreamCANSignals',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.autodemo.Empty,
  proto.autodemo.CANSignal,
  /**
   * @param {!proto.autodemo.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.autodemo.CANSignal.deserializeBinary
);


/**
 * @param {!proto.autodemo.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.autodemo.CANSignal>}
 *     The XHR Node Readable Stream
 */
proto.autodemo.CANSignalServiceClient.prototype.streamCANSignals =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/autodemo.CANSignalService/StreamCANSignals',
      request,
      metadata || {},
      methodDescriptor_CANSignalService_StreamCANSignals);
};


/**
 * @param {!proto.autodemo.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.autodemo.CANSignal>}
 *     The XHR Node Readable Stream
 */
proto.autodemo.CANSignalServicePromiseClient.prototype.streamCANSignals =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/autodemo.CANSignalService/StreamCANSignals',
      request,
      metadata || {},
      methodDescriptor_CANSignalService_StreamCANSignals);
};


module.exports = proto.autodemo;

